language: node_js
node_js:
  - "0.12"
  - "0.10"

env:
  - APP_SECRET=123123123123
  - PORT=8080

services:
  - mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'